select_server:
	python select_server.py
server:
	python server.py
process_server:
	python process_server.py
thread_server:
	python thread_server.py
thread_lock_server:
	python thread_lock_server.py
client:
	python client.py